### ISSUE TITLE
Replacing file in split

### ISSUE THREAD

**Issue by NLSurfMan** [parallaxe/OpenInSplittedTab#9]
Hi, 
I have tried your plugin in IntelliJ IDEA and I like it. I have one enhancement request though: if I open a second file this way, it replaces the previous file in the splitter. Can you make it so that the previous file stays open?

**Comment by parallaxe** [comment]
The current action works as intended and I don't want to change that. Though, I added a second action that doesn't replace the previous tab (named "Open in splitted (new) tab"). I pushed it on a separate branch (https://github.com/parallaxe/OpenInSplittedTab/tree/Feature-9) - could you do me a favour and test if it fits your purpose?

**Comment by NLSurfMan** [comment]
I like it. It does the job perfectly!

**Comment by parallaxe** [comment]
Great to hear that, thanks for testing!
